export const POST = {
  LOAD_SUCCESS: 'LOAD_SUCCESS',
  LOAD_FAILED: 'LOAD_FAILED',
  LOADING: 'LOADING',
  FETCH_POST: 'FETCH_POST',
  ADD_POST: 'ADD_POST',
  ADD_POST_ASYNC: 'ADD_POST_ASYNC',
  SEARCH_POST: 'SEARCH_POST',
  SEARCH_POST_ASYNC: 'SEARCH_POST_ASYNC',
};

export const FORM = {
  ERROR: 'ERROR',
  ERROR_ASYNC: 'ERROR_ASYNC',
  CLEAR_ERROR: 'CLEAR_ERROR',
}
