export const POST = {
  LOAD_SUCCESS: 'LOAD_SUCCESS',
  LOAD_FAILED: 'LOAD_FAILED',
  LOADING: 'LOADING',
  FETCH_POST: 'FETCH_POST',
  ADD_POST: 'ADD_POST',
  ADD_POST_ASYNC: 'ADD_POST_ASYNC',
  SEARCH_POST: 'SEARCH_POST',
  SEARCH_POST_ASYNC: 'SEARCH_POST_ASYNC',
};

export const FORM = {
  ERROR: 'ERROR',
  ERROR_ASYNC: 'ERROR_ASYNC',
  CLEAR_ERROR: 'CLEAR_ERROR',
};

export const USER = {
  SIGN_IN: 'SIGN_IN',
  SIGN_OUT: 'SIGN_OUT',
  ADD_USER: 'ADD_USER',
  FETCH_USERS: 'FETCH_USERS',
  FETCH_SUCCESS: 'FETCH_SUCCESS',
};

export const COMMENT = {
  ADD_COMMENT: 'ADD_COMMENT',
  FETCH_COMMENTS: 'FETCH_COMMENTS',
  FETCH_COMMENT_SUCCESS: 'FETCH_COMMENT_SUCCESS',
};
